"""add workflow run summary

Revision ID: 77dfebdfb8fb
Revises: eb92b8f8b6c1
Create Date: 2026-08-20 20:33:37.253298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77dfebdfb8fb'
down_revision: Union[str, None] = 'eb92b8f8b6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'summary')
    # ### end Alembic commands ###